version: "3.10"

services:
  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SERVER: db
      POSTGRES_DB: postgres

  app:
    container_name: app
    image: pumpka/test-project
    entrypoint: ./docker-entrypoint.sh
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    environment:
      SECRET_KEY: django-insecure-0n-njadk2$v*ifoj9lwra+m#4z(2rb6^wte2sbu4hwuk*ceej*
      STRIPE_API_KEY: sk_test_4eC39HqLyjWDarjtT1zdp7dc
      STRIPE_CLIENT_KEY: pk_test_TYooMQauvdEDq54NiTphI7jx
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SERVER: db
      POSTGRES_DB: postgres
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: 123123
      DJANGO_SUPERUSER_EMAIL: example@example.com
      DEV: "false"
      SERVER_NAMES: localhost,127.0.0.1

volumes:
  postgres_db:
